### ISSUE TITLE
Found version conflict(s) in library dependencies;

### ISSUE THREAD

**Issue by Ben-Mark** [playframework/play-java-starter-example#75] opened 2018-07-21 07:42 UTC
Cant believe that the official java starter project has these conflicts

sbt build log!@#

[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* org.webjars:webjars-locator-core:0.33 is selected over 0.32
[warn] 	    +- com.typesafe:npm_2.12:1.2.1                        (depends on 0.32)
[warn] 	    +- com.typesafe.sbt:sbt-web:1.4.3 (scalaVersion=2.12, sbtVersion=1.0) (depends on 0.32)
[warn] 	* org.codehaus.plexus:plexus-utils:3.0.17 is selected over {2.1, 1.5.5}
[warn] 	    +- org.apache.maven:maven-settings:3.2.2              (depends on 3.0.17)
[warn] 	    +- org.apache.maven:maven-repository-metadata:3.2.2   (depends on 3.0.17)
[warn] 	    +- org.apache.maven:maven-aether-provider:3.2.2       (depends on 3.0.17)
[warn] 	    +- org.apache.maven:maven-model:3.2.2                 (depends on 3.0.17)
[warn] 	    +- org.apache.maven:maven-core:3.2.2                  (depends on 3.0.17)
[warn] 	    +- org.apache.maven:maven-artifact:3.2.2              (depends on 3.0.17)
[warn] 	    +- org.apache.maven:maven-settings-builder:3.2.2      (depends on 3.0.17)
[warn] 	    +- org.apache.maven:maven-model-builder:3.2.2         (depends on 3.0.17)
[warn] 	    +- org.sonatype.plexus:plexus-sec-dispatcher:1.3      (depends on 1.5.5)
[warn] 	    +- org.eclipse.sisu:org.eclipse.sisu.plexus:0.0.0.M5  (depends on 2.1)
[warn] 	* com.google.guava:guava:23.0 is selected over {10.0.1, 16.0, 20.0}
[warn] 	    +- io.methvin:directory-watcher:0.3.2                 (depends on 23.0)
[warn] 	    +- com.fasterxml.jackson.datatype:jackson-datatype-guava:2.8.8 (depends on 10.0.1)
[warn] 	    +- org.eclipse.sisu:org.eclipse.sisu.plexus:0.0.0.M5  (depends on 10.0.1)
[warn] 	    +- com.spotify:docker-client:8.9.0                    (depends on 10.0.1)
[warn] Run 'evicted' to see detailed eviction warnings
[info] Loading settings from build.sbt ...

**Comment by ghost** [comment] 2018-09-24 15:51
[](url)

**Comment by ghost** [comment] 2018-09-24 15:52
Duplicate of #

**Comment by marcospereira** [comment] 2018-09-24 19:15
Hi,

This is only sbt being a little too noisy about eviction warnings, and the project works as expected. Did you find any problem running the project?

**Closed as completed** 2018-09-27 14:15 UTC
