### ISSUE TITLE
This doesn't work?

### ISSUE THREAD

**Issue by stephenjfox** [playframework/play-java-starter-example#80] opened 2018-10-08 20:40 UTC
I cloned the project and loaded up in IntelliJ 2018.2.4, and everything important (`conf/routes`, `application.conf`, all of the Twirl templates) is **doesn't compile.**

It's red throughout the codebase. 
I really appreciate the effort you've gone through to make a workable example for the community, as they are severely lacking, but this one does not work.

If I am doing something wrong (I `git clone <repo link>`'d, saw that stuff was still not compiling, deleted SBT stuff, saw the same output) can anyone tell me where and why?

**Comment by raboof** [comment] 2018-10-09 08:42
Interesting! I just tried it and it seems to work for me. How did you import the project? For me Intellij automatically picked the Gradle importer, which successfully imported the project.

**Comment by stephenjfox** [comment] 2018-10-09 14:38
I'll try it again this morning, and report back.


2018년 10월 9일 (화) 오전 2:42, Arnout Engelen <notifications@github.com>님이 작성:

**Comment by marcospereira** [comment] 2018-10-09 19:40
Hi @stephenjfox,

Just to confirm that you need to [install the Scala Plugin](https://www.jetbrains.com/help/idea/discover-intellij-idea-for-scala.html) to have [Play support in IntelliJ](https://www.jetbrains.com/help/idea/getting-started-with-play-2-x.html).

I'm closing this one since I was not able to reproduce it either. But please, if you have more information, add it here and we can reopen this issue if necessary.

Best.

**Closed as completed by marcospereira** 2018-10-09 19:40 UTC

**Comment by stephenjfox** [comment] 2018-10-09 20:23
I got the same result.
I'm working against the `2.6.x` branch, because that branch uses Gradle (what I need for my company).

I've just finished watching the Gradle and SBT builds run (which took too long to record), and the application starts but the IDE is still full of errors.

However, with the SBT console in IntelliJ IDEA, I was able to run the app, which leads me to a related question:
**Do I need to run with SBT**, while building with both SBT **and** Gradle?
