### ISSUE TITLE
sbt dist generates bat file that throws an error

### ISSUE THREAD

**Issue by Zohar2506** [playframework/play-java-starter-example#70] opened 2018-06-05 07:41 UTC
After running sbt dist with the play-java-starter-example the following error is thrown while running the .bat file:

```
The input line is too long.
The syntax of the command is incorrect.
```

**Comment by marcospereira** [comment] 2018-06-06 18:14
Hi @Zohar2506,

The possible solutions are listed here:

https://sbt-native-packager.readthedocs.io/en/stable/recipes/longclasspath.html

The problem is that there is a limit of how long commands can be in Windows:

https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation

Best.

**Comment by marcospereira** [comment] 2018-09-24 19:16
Closing this since there is a configuration in sbt-native-packager to solve the problem.

**Closed as completed by marcospereira** 2018-09-24 19:16 UTC
